/**
 * The `kibborg serve` overlay.
 *
 * Serving is the same profile with a different transport: the rows that mount
 * the HTTP carrier are added and the terminal client half is switched off, so
 * the process owns a server instead of answering one task. Everything the
 * server does — sessions, tools, settings — comes from the composition it
 * already mounts; only the way in changes.
 *
 * The token is never written into the overlay: the row reads it from the
 * environment, so a generated file in the temporary directory cannot leak it.
 * @module @kibborg/cli/serve
 */

/** What one `kibborg serve` invocation asked for. */
export interface ServeOptions {
  /** Bind address. */
  readonly host: string
  /** TCP port. */
  readonly port: number
  /** Shared token; absent means loopback-only serving. */
  readonly token?: string
  /** Authorities served beyond loopback. */
  readonly trustedHosts: readonly string[]
  /** Print one access-log line per request. */
  readonly log: boolean
  /** Advertise this server over mDNS. */
  readonly mdns?: boolean
  /** Instance name the mDNS record carries; empty asks the plugin to derive one. */
  readonly instance?: string
}

/** Whether an address is this machine only. */
export function isLoopbackAddress(host: string): boolean {
  return host === '127.0.0.1' || host === '::1' || host === 'localhost'
}

/**
 * Decide whether this deployment may start.
 *
 * A reachable server without a token is an open server; the refusal happens
 * before the profile boots, so an operator learns about it from the launcher
 * rather than from a stranger's request.
 * @param options - the resolved serve options.
 * @returns the failure message, or `undefined` when the deployment is allowed.
 */
export function serveRefusal(options: ServeOptions): string | undefined {
  const offLoopback = !isLoopbackAddress(options.host)
  const token = options.token ?? process.env['KIBBORG_SERVER_TOKEN'] ?? ''
  if (offLoopback && token === '') {
    return `kibborg: serving on ${options.host} needs a token; pass --token or set KIBBORG_SERVER_TOKEN (loopback is the default)`
  }
  if (options.trustedHosts.length > 0 && token === '') {
    return 'kibborg: --trusted-host declares a reachable authority, which needs a token'
  }
  return undefined
}

/**
 * Build the overlay that turns the CLI profile into a server.
 * @param options - the resolved serve options.
 * @returns the patch document to write beside this invocation's other overlays.
 */
export function buildServeOverlay(options: ServeOptions): string {
  const trusted = options.trustedHosts.map(host => `          - ${JSON.stringify(host)}`).join('\n')
  return `# Generated by \`kibborg serve\`. The token is read from the environment.
- insert:
    - id: webserver
      name: '@deepseek-ai/dsh-host-webserver'
      config:
        host: ${JSON.stringify(options.host)}
        port: ${String(options.port)}

    - id: kibborg-serve
      name: '@kibborg/server'
      config:
        token: !!js process.env.KIBBORG_SERVER_TOKEN ?? ''
        trustedHosts:
${trusted === '' ? '          []' : trusted}
        log: ${options.log ? 'true' : 'false'}
        mdns: !!js process.env.KIBBORG_SERVE_MDNS === '1'
        instance: !!js process.env.KIBBORG_SERVE_INSTANCE ?? ''
        # The mDNS record advertises this port, so it has to be the real one.
        port: ${String(options.port)}

# The terminal client half answers one invocation and then asks the process to
# exit; a server must outlive that, so the row is switched off here.
- id: kibborg-client
  disabled: true
`
}
