/**
 * Tool selection for one invocation.
 *
 * The harness composes tools as loader rows, so restricting them is a
 * composition change rather than a runtime filter: an invocation that asks for a
 * smaller tool set gets a generated patch overlay that disables the rows it did
 * not ask for. That keeps one registry (the composition) and one enforcement
 * point (the loader) instead of adding a second filter the model could bypass.
 * @module @kibborg/cli/tool-filter
 */

/** Loader rows per model-facing tool name, as the tool catalog composes them. */
const TOOL_ROWS: Readonly<Record<string, readonly string[]>> = {
  read: ['tool-fs'],
  write: ['tool-fs'],
  edit: ['tool-fs'],
  str_replace_editor: ['tool-str-replace-editor'],
  grep: ['tool-fs-search'],
  glob: ['tool-fs-search'],
  bash: ['tool-bash'],
  pwsh: ['tool-pwsh'],
  todo_write: ['tool-todo'],
  goal: ['tool-goal'],
  skill: ['tool-skill'],
  skill_manage: ['skill-manager'],
  subagent: ['tool-subagent'],
  subagent_fork: ['tool-subagent-fork'],
  subagent_report: ['tool-subagent-report'],
  send_message: ['tool-subagent-control'],
  list_agents: ['tool-subagent-control', 'tool-subagent-list-agents'],
  jobs: ['tool-jobs'],
  workflow: ['tool-workflow'],
  ralph: ['tool-ralph'],
  web_search: ['tool-web'],
  web_fetch: ['tool-web'],
  ask_user_question: ['tool-ask-user'],
  session_query: ['tool-session-query'],
  terminal_open: ['tool-terminal'],
  terminal_read: ['tool-terminal'],
  terminal_send: ['tool-terminal'],
  terminal_signal: ['tool-terminal'],
  terminal_list: ['tool-terminal'],
  terminal_close: ['tool-terminal'],
  lsp: ['tool-lsp'],
  cordis: ['tool-cordis'],
}

/** Every row this module can address. */
export const ADDRESSABLE_ROWS: readonly string[] = [...new Set(Object.values(TOOL_ROWS).flat())].sort()

/** What the invocation asked for. */
export interface ToolSelection {
  /** Tool names to keep; when present, every other row is disabled. */
  readonly tools?: readonly string[]
  /** Tool names to disable, applied after {@link tools}. */
  readonly deny?: readonly string[]
}

/** Resolve one name to the rows it owns; an unknown name resolves to itself when it looks like a row. */
function rowsOf(name: string): readonly string[] {
  const known = TOOL_ROWS[name]
  if (known !== undefined) return known
  const trimmed = name.trim()
  return trimmed.startsWith('tool-') || trimmed.includes('-') ? [trimmed] : []
}

/**
 * Build the patch overlay that restricts the composed tool set.
 * @param selection - the allow list and deny list from the command line.
 * @returns the overlay's YAML text, or `undefined` when nothing is restricted.
 */
export function buildToolOverlay(selection: ToolSelection): string | undefined {
  const allow = (selection.tools ?? []).map(name => name.trim()).filter(name => name !== '')
  const deny = (selection.deny ?? []).map(name => name.trim()).filter(name => name !== '')
  if (allow.length === 0 && deny.length === 0) return undefined

  const kept = new Set(allow.flatMap(rowsOf))
  const disabled = new Set<string>()
  if (allow.length > 0) {
    for (const row of ADDRESSABLE_ROWS) {
      if (!kept.has(row)) disabled.add(row)
    }
  }
  for (const name of deny) {
    for (const row of rowsOf(name)) disabled.add(row)
  }
  // An explicit allow wins over a deny for the same row: the caller named it twice.
  for (const row of kept) disabled.delete(row)
  if (disabled.size === 0) return undefined

  const header = [
    '# Generated by kibborg from --tools/--allow/--deny: the rows this invocation',
    '# did not ask for are disabled rather than removed, so the composition above',
    '# stays intact and each row keeps its own owner.',
  ]
  const rows = [...disabled].sort().map(row => `- id: ${row}\n  disabled: true`)
  return `${header.join('\n')}\n${rows.join('\n')}\n`
}
